#!/bin/bash

declare -a foldersToRemove=("symlinksToFiles" "symlinkToTheFolder" "notOrigins" "origins")
for folder in "${foldersToRemove[@]}"; do
  if [ -e $folder ]; then
    rm -rf $folder
  fi
done

